networks:
  slurmtack-net:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8077:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    networks:
      - slurmtack-net
    depends_on:
      - slurmtack
    restart: unless-stopped

  slurmtack:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    networks:
      - slurmtack-net
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    env_file: .env
    volumes:
      - .:/data
      - ${HOME}/.ssh/id_rsa:/run/secrets/slurmtack-ssh-key:ro
      - /etc/hosts:/etc/hosts:ro
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - slurmtack-net
    restart: unless-stopped
