services:
  slurmtack:
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: host
    env_file: .env
    volumes:
      - slurmtack-data:/data
      - ../build/output/placeholder-agent.sif:/data/placeholder-agent.sif:ro
      - ${HOME}/.ssh/id_rsa:/run/secrets/slurmtack-ssh-key:ro
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    network_mode: host
    restart: unless-stopped

volumes:
  slurmtack-data:
